window.esdocSearchIndex = [
  [
    "influx/src/backoff/constant.js~constantbackoff",
    "class/src/backoff/constant.js~ConstantBackoff.html",
    "<span>ConstantBackoff</span> <span class=\"search-result-import-path\">influx/src/backoff/constant.js</span>",
    "class"
  ],
  [
    "influx/src/backoff/exponential.js~exponentialbackoff",
    "class/src/backoff/exponential.js~ExponentialBackoff.html",
    "<span>ExponentialBackoff</span> <span class=\"search-result-import-path\">influx/src/backoff/exponential.js</span>",
    "class"
  ],
  [
    "influx/src/builder.js~expression",
    "class/src/builder.js~Expression.html",
    "<span>Expression</span> <span class=\"search-result-import-path\">influx/src/builder.js</span>",
    "class"
  ],
  [
    "influx/src/index.js~influxdb",
    "class/src/index.js~InfluxDB.html",
    "<span>InfluxDB</span> <span class=\"search-result-import-path\">influx/src/index.js</span>",
    "class"
  ],
  [
    "influx/src/builder.js~measurement",
    "class/src/builder.js~Measurement.html",
    "<span>Measurement</span> <span class=\"search-result-import-path\">influx/src/builder.js</span>",
    "class"
  ],
  [
    "influx/src/pool.js~pool",
    "class/src/pool.js~Pool.html",
    "<span>Pool</span> <span class=\"search-result-import-path\">influx/src/pool.js</span>",
    "class"
  ],
  [
    "influx/src/grammar/times.js~precision",
    "variable/index.html#static-variable-Precision",
    "<span>Precision</span> <span class=\"search-result-import-path\">influx/src/grammar/times.js</span>",
    "variable"
  ],
  [
    "influx/src/grammar/ds.js~raw",
    "class/src/grammar/ds.js~Raw.html",
    "<span>Raw</span> <span class=\"search-result-import-path\">influx/src/grammar/ds.js</span>",
    "class"
  ],
  [
    "influx/src/pool.js~requesterror",
    "class/src/pool.js~RequestError.html",
    "<span>RequestError</span> <span class=\"search-result-import-path\">influx/src/pool.js</span>",
    "class"
  ],
  [
    "influx/src/results.js~resulterror",
    "class/src/results.js~ResultError.html",
    "<span>ResultError</span> <span class=\"search-result-import-path\">influx/src/results.js</span>",
    "class"
  ],
  [
    "influx/src/schema.js~schema",
    "class/src/schema.js~Schema.html",
    "<span>Schema</span> <span class=\"search-result-import-path\">influx/src/schema.js</span>",
    "class"
  ],
  [
    "influx/src/pool.js~servicenotavailableerror",
    "class/src/pool.js~ServiceNotAvailableError.html",
    "<span>ServiceNotAvailableError</span> <span class=\"search-result-import-path\">influx/src/pool.js</span>",
    "class"
  ],
  [
    "influx/src/results.js~assertnoerrors",
    "function/index.html#static-function-assertNoErrors",
    "<span>assertNoErrors</span> <span class=\"search-result-import-path\">influx/src/results.js</span>",
    "function"
  ],
  [
    "influx/src/grammar/times.js~casttimestamp",
    "function/index.html#static-function-castTimestamp",
    "<span>castTimestamp</span> <span class=\"search-result-import-path\">influx/src/grammar/times.js</span>",
    "function"
  ],
  [
    "influx/src/schema.js~coercebadly",
    "function/index.html#static-function-coerceBadly",
    "<span>coerceBadly</span> <span class=\"search-result-import-path\">influx/src/schema.js</span>",
    "function"
  ],
  [
    "influx/src/grammar/times.js~datetotime",
    "function/index.html#static-function-dateToTime",
    "<span>dateToTime</span> <span class=\"search-result-import-path\">influx/src/grammar/times.js</span>",
    "function"
  ],
  [
    "influx/src/grammar/escape.js~escape",
    "variable/index.html#static-variable-escape",
    "<span>escape</span> <span class=\"search-result-import-path\">influx/src/grammar/escape.js</span>",
    "variable"
  ],
  [
    "influx/src/grammar/times.js~formatdate",
    "function/index.html#static-function-formatDate",
    "<span>formatDate</span> <span class=\"search-result-import-path\">influx/src/grammar/times.js</span>",
    "function"
  ],
  [
    "influx/src/grammar/times.js~isoortimetodate",
    "function/index.html#static-function-isoOrTimeToDate",
    "<span>isoOrTimeToDate</span> <span class=\"search-result-import-path\">influx/src/grammar/times.js</span>",
    "function"
  ],
  [
    "influx/src/results.js~parse",
    "function/index.html#static-function-parse",
    "<span>parse</span> <span class=\"search-result-import-path\">influx/src/results.js</span>",
    "function"
  ],
  [
    "influx/src/results.js~parsesingle",
    "function/index.html#static-function-parseSingle",
    "<span>parseSingle</span> <span class=\"search-result-import-path\">influx/src/results.js</span>",
    "function"
  ],
  [
    "influx/src/grammar/times.js~tonanodate",
    "function/index.html#static-function-toNanoDate",
    "<span>toNanoDate</span> <span class=\"search-result-import-path\">influx/src/grammar/times.js</span>",
    "function"
  ],
  [
    "",
    "test-file/unit/backoff.test.js.html#lineNumber5",
    "backoff strategies",
    "test"
  ],
  [
    "",
    "test-file/unit/backoff.test.js.html#lineNumber6",
    "backoff strategies constant strategy",
    "test"
  ],
  [
    "",
    "test-file/unit/backoff.test.js.html#lineNumber7",
    "backoff strategies constant strategy appears to work",
    "test"
  ],
  [
    "",
    "test-file/unit/backoff.test.js.html#lineNumber33",
    "backoff strategies exponential strategy",
    "test"
  ],
  [
    "",
    "test-file/unit/backoff.test.js.html#lineNumber34",
    "backoff strategies exponential strategy appears to work",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber4",
    "grammar",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber6",
    "grammar ",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber8",
    "grammar  ",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber32",
    "grammar converts a nanoseconds timestamp to a nano date",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber38",
    "grammar converts a nanoseconds timestamp with trailing zeroes to a nano date",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber14",
    "grammar does not escape raw values",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber17",
    "grammar escapes backslashes (issues #486, #516)",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber22",
    "grammar escapes complex values (issue #242)",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber44",
    "grammar formatting",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber48",
    "grammar formatting formats millisecond dates",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber45",
    "grammar formatting formats nanosecond dates",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber52",
    "grammar parsing",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber53",
    "grammar parsing parses ISO dates correctly",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber86",
    "grammar parsing parses numeric `h` timestamps",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber81",
    "grammar parsing parses numeric `m` timestamps",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber71",
    "grammar parsing parses numeric `ms` timestamps",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber59",
    "grammar parsing parses numeric `ns` timestamps",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber76",
    "grammar parsing parses numeric `s` timestamps",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber65",
    "grammar parsing parses numeric `u` timestamps",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber92",
    "grammar timestamp casting",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber111",
    "grammar timestamp casting accepts strings, numbers liternally",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber93",
    "grammar timestamp casting casts dates into timestamps",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber102",
    "grammar timestamp casting casts nanodates into timestamps",
    "test"
  ],
  [
    "",
    "test-file/unit/grammar.test.js.html#lineNumber115",
    "grammar timestamp casting throws on non-numeric strings",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber5",
    "influxdb",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber6",
    "influxdb constructor",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber62",
    "influxdb constructor parses cluster configs",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber25",
    "influxdb constructor parses dsns",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber82",
    "influxdb constructor parses parses schema",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber44",
    "influxdb constructor parses single configs",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber7",
    "influxdb constructor uses default options",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber122",
    "influxdb methods",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber732",
    "influxdb methods .alterRetentionPolicy",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber742",
    "influxdb methods .alterRetentionPolicy creates default policies",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber734",
    "influxdb methods .alterRetentionPolicy creates non-default policies",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber378",
    "influxdb methods .createContinuousQuery()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber390",
    "influxdb methods .createContinuousQuery() fills in default DB",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber379",
    "influxdb methods .createContinuousQuery() queries correctly no resample",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber383",
    "influxdb methods .createContinuousQuery() queries correctly with resample",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber387",
    "influxdb methods .createContinuousQuery() throws if DB unspecified",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber183",
    "influxdb methods .createDatabase()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber713",
    "influxdb methods .createRetentionPolicy",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber723",
    "influxdb methods .createRetentionPolicy creates default policies",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber715",
    "influxdb methods .createRetentionPolicy creates non-default policies",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber324",
    "influxdb methods .createUser()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber329",
    "influxdb methods .createUser() works with admin specified == false",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber325",
    "influxdb methods .createUser() works with admin specified == true",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber333",
    "influxdb methods .createUser() works with admin unspecified",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber396",
    "influxdb methods .dropContinuousQuery()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber404",
    "influxdb methods .dropContinuousQuery() fills in default DB",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber397",
    "influxdb methods .dropContinuousQuery() queries correctly",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber401",
    "influxdb methods .dropContinuousQuery() throws if DB unspecified",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber189",
    "influxdb methods .dropDatabase()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber273",
    "influxdb methods .dropMeasurement()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber280",
    "influxdb methods .dropSeries()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber304",
    "influxdb methods .dropSeries() drops with both",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber286",
    "influxdb methods .dropSeries() drops with only from clause by builder",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber282",
    "influxdb methods .dropSeries() drops with only from clause by string",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber297",
    "influxdb methods .dropSeries() drops with only where clause by builder",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber290",
    "influxdb methods .dropSeries() drops with only where clause by string",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber195",
    "influxdb methods .dropShard()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber374",
    "influxdb methods .dropUser()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber199",
    "influxdb methods .getDatabaseNames()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber205",
    "influxdb methods .getMeasurements()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber215",
    "influxdb methods .getSeries() from all",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber250",
    "influxdb methods .getSeries() from single",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber315",
    "influxdb methods .getUsers()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber366",
    "influxdb methods .grantAdminPrivilege()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber338",
    "influxdb methods .grantPrivilege()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber346",
    "influxdb methods .grantPrivilege() fills in default DB",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber339",
    "influxdb methods .grantPrivilege() queries correctly",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber343",
    "influxdb methods .grantPrivilege() throws if DB unspecified",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber620",
    "influxdb methods .query",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber634",
    "influxdb methods .query parses query output",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber670",
    "influxdb methods .query passes in options",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber683",
    "influxdb methods .query rewrites nanosecond precisions",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber622",
    "influxdb methods .query runs raw queries",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber657",
    "influxdb methods .query selects from multiple",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber696",
    "influxdb methods .query uses placeholders",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber370",
    "influxdb methods .revokeAdminPrivilege()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber352",
    "influxdb methods .revokePrivilege()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber360",
    "influxdb methods .revokePrivilege() fills in default DB",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber353",
    "influxdb methods .revokePrivilege() queries correctly",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber357",
    "influxdb methods .revokePrivilege() throws if DB unspecified",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber410",
    "influxdb methods .showContinousQueries()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber418",
    "influxdb methods .showContinousQueries() fills in default DB",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber411",
    "influxdb methods .showContinousQueries() queries correctly",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber415",
    "influxdb methods .showContinousQueries() throws if DB unspecified",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber424",
    "influxdb methods .writePoints()",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber589",
    "influxdb methods .writePoints() accepts nanoseconds (as ms)",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber604",
    "influxdb methods .writePoints() accepts timestamp overriding",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber479",
    "influxdb methods .writePoints() can accept a schema at runtime",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber548",
    "influxdb methods .writePoints() handles lack of fields",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber535",
    "influxdb methods .writePoints() handles lack of tags",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber561",
    "influxdb methods .writePoints() handles multiple tags",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber508",
    "influxdb methods .writePoints() throws on schema violations",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber460",
    "influxdb methods .writePoints() uses a schema to coerce",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber444",
    "influxdb methods .writePoints() writes using default options without a schema",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber425",
    "influxdb methods .writePoints() writes with all options specified without a schema",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber574",
    "influxdb methods .writePoints() writes with the .writeMeasurement method",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber751",
    "influxdb methods drops retention policies",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber756",
    "influxdb methods shows retention policies",
    "test"
  ],
  [
    "",
    "test-file/unit/influx.test.js.html#lineNumber781",
    "influxdb methods shows shards",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber12",
    "pool",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber58",
    "pool attempts to make an https request",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber179",
    "pool backoff",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber239",
    "pool backoff constant",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber247",
    "pool backoff constant should disable hosts if backoff delay is greater than zero",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber260",
    "pool backoff constant should not disable hosts if backoff delay is zero",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber180",
    "pool backoff exponential",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber203",
    "pool backoff exponential should back off if failures continue",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber187",
    "pool backoff exponential should error if there are no available hosts",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber198",
    "pool backoff exponential should reenable hosts after the backoff expires",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber220",
    "pool backoff exponential should reset backoff after success",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber151",
    "pool calls back immediately on un-retryable error",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber139",
    "pool fails if too many errors happen",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber77",
    "pool handles unicode chunks correctly",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber63",
    "pool passes through request options",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber163",
    "pool pings servers",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber83",
    "pool request generators",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber105",
    "pool request generators discards responses",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber113",
    "pool request generators errors if JSON parsing fails",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber89",
    "pool request generators includes request query strings and bodies",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber84",
    "pool request generators makes a text request",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber108",
    "pool request generators parses JSON responses",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber134",
    "pool retries on a request error",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber173",
    "pool times out in pings",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber122",
    "pool times out requests",
    "test"
  ],
  [
    "",
    "test-file/unit/pool.test.js.html#lineNumber71",
    "pool valid request data content length",
    "test"
  ],
  [
    "",
    "test-file/unit/builder.test.js.html#lineNumber4",
    "query builder",
    "test"
  ],
  [
    "",
    "test-file/unit/builder.test.js.html#lineNumber26",
    "query builder expression builder",
    "test"
  ],
  [
    "",
    "test-file/unit/builder.test.js.html#lineNumber77",
    "query builder expression builder ",
    "test"
  ],
  [
    "",
    "test-file/unit/builder.test.js.html#lineNumber27",
    "query builder expression builder creates basic queries",
    "test"
  ],
  [
    "",
    "test-file/unit/builder.test.js.html#lineNumber30",
    "query builder expression builder inserts data types correctly",
    "test"
  ],
  [
    "",
    "test-file/unit/builder.test.js.html#lineNumber54",
    "query builder expression builder throws when using a flagged regex",
    "test"
  ],
  [
    "",
    "test-file/unit/builder.test.js.html#lineNumber57",
    "query builder expression builder throws when using un-stringifyable object",
    "test"
  ],
  [
    "",
    "test-file/unit/builder.test.js.html#lineNumber5",
    "query builder measurement builder",
    "test"
  ],
  [
    "",
    "test-file/unit/builder.test.js.html#lineNumber19",
    "query builder measurement builder builds with name and db",
    "test"
  ],
  [
    "",
    "test-file/unit/builder.test.js.html#lineNumber9",
    "query builder measurement builder builds with name and rp",
    "test"
  ],
  [
    "",
    "test-file/unit/builder.test.js.html#lineNumber12",
    "query builder measurement builder builds with name, rp, and db",
    "test"
  ],
  [
    "",
    "test-file/unit/builder.test.js.html#lineNumber6",
    "query builder measurement builder builds with only name",
    "test"
  ],
  [
    "",
    "test-file/unit/builder.test.js.html#lineNumber22",
    "query builder measurement builder throws when a name is omitted",
    "test"
  ],
  [
    "",
    "test-file/unit/result.test.js.html#lineNumber4",
    "results",
    "test"
  ],
  [
    "",
    "test-file/unit/result.test.js.html#lineNumber5",
    "results parses a empty result",
    "test"
  ],
  [
    "",
    "test-file/unit/result.test.js.html#lineNumber48",
    "results parses a results with second-precision",
    "test"
  ],
  [
    "",
    "test-file/unit/result.test.js.html#lineNumber22",
    "results parses a simple table of results",
    "test"
  ],
  [
    "",
    "test-file/unit/result.test.js.html#lineNumber71",
    "results parses alternate epochs",
    "test"
  ],
  [
    "",
    "test-file/unit/result.test.js.html#lineNumber168",
    "results parses empty series",
    "test"
  ],
  [
    "",
    "test-file/unit/result.test.js.html#lineNumber174",
    "results parses empty values",
    "test"
  ],
  [
    "",
    "test-file/unit/result.test.js.html#lineNumber113",
    "results parses grouped results",
    "test"
  ],
  [
    "",
    "test-file/unit/result.test.js.html#lineNumber184",
    "results throws error on an errorful series",
    "test"
  ],
  [
    "",
    "test-file/unit/schema.test.js.html#lineNumber5",
    "schema",
    "test"
  ],
  [
    "",
    "test-file/unit/schema.test.js.html#lineNumber33",
    "schema basic schema",
    "test"
  ],
  [
    "",
    "test-file/unit/schema.test.js.html#lineNumber47",
    "schema basic schema accepts partial data",
    "test"
  ],
  [
    "",
    "test-file/unit/schema.test.js.html#lineNumber76",
    "schema basic schema allows valid tags",
    "test"
  ],
  [
    "",
    "test-file/unit/schema.test.js.html#lineNumber34",
    "schema basic schema coerces data correctly",
    "test"
  ],
  [
    "",
    "test-file/unit/schema.test.js.html#lineNumber52",
    "schema basic schema coerces numeric string data",
    "test"
  ],
  [
    "",
    "test-file/unit/schema.test.js.html#lineNumber57",
    "schema basic schema strips null and undefined values",
    "test"
  ],
  [
    "",
    "test-file/unit/schema.test.js.html#lineNumber83",
    "schema basic schema throws if invalid fields are provided",
    "test"
  ],
  [
    "",
    "test-file/unit/schema.test.js.html#lineNumber80",
    "schema basic schema throws if invalid tags are provided",
    "test"
  ],
  [
    "",
    "test-file/unit/schema.test.js.html#lineNumber64",
    "schema basic schema throws if wrong data type provided (bool)",
    "test"
  ],
  [
    "",
    "test-file/unit/schema.test.js.html#lineNumber68",
    "schema basic schema throws if wrong data type provided (float)",
    "test"
  ],
  [
    "",
    "test-file/unit/schema.test.js.html#lineNumber72",
    "schema basic schema throws if wrong data type provided (int)",
    "test"
  ],
  [
    "",
    "test-file/unit/schema.test.js.html#lineNumber20",
    "schema coerceBadly",
    "test"
  ],
  [
    "",
    "test-file/unit/schema.test.js.html#lineNumber21",
    "schema coerceBadly apparently works",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/backoff/backoff.js",
    "file/src/backoff/backoff.js.html",
    "src/backoff/backoff.js",
    "file"
  ],
  [
    "src/backoff/constant.js",
    "file/src/backoff/constant.js.html",
    "src/backoff/constant.js",
    "file"
  ],
  [
    "src/backoff/constant.js~constantbackoff#constructor",
    "class/src/backoff/constant.js~ConstantBackoff.html#instance-constructor-constructor",
    "src/backoff/constant.js~ConstantBackoff#constructor",
    "method"
  ],
  [
    "src/backoff/constant.js~constantbackoff#getdelay",
    "class/src/backoff/constant.js~ConstantBackoff.html#instance-method-getDelay",
    "src/backoff/constant.js~ConstantBackoff#getDelay",
    "method"
  ],
  [
    "src/backoff/constant.js~constantbackoff#next",
    "class/src/backoff/constant.js~ConstantBackoff.html#instance-method-next",
    "src/backoff/constant.js~ConstantBackoff#next",
    "method"
  ],
  [
    "src/backoff/constant.js~constantbackoff#reset",
    "class/src/backoff/constant.js~ConstantBackoff.html#instance-method-reset",
    "src/backoff/constant.js~ConstantBackoff#reset",
    "method"
  ],
  [
    "src/backoff/exponential.js",
    "file/src/backoff/exponential.js.html",
    "src/backoff/exponential.js",
    "file"
  ],
  [
    "src/backoff/exponential.js~exponentialbackoff#constructor",
    "class/src/backoff/exponential.js~ExponentialBackoff.html#instance-constructor-constructor",
    "src/backoff/exponential.js~ExponentialBackoff#constructor",
    "method"
  ],
  [
    "src/backoff/exponential.js~exponentialbackoff#getdelay",
    "class/src/backoff/exponential.js~ExponentialBackoff.html#instance-method-getDelay",
    "src/backoff/exponential.js~ExponentialBackoff#getDelay",
    "method"
  ],
  [
    "src/backoff/exponential.js~exponentialbackoff#next",
    "class/src/backoff/exponential.js~ExponentialBackoff.html#instance-method-next",
    "src/backoff/exponential.js~ExponentialBackoff#next",
    "method"
  ],
  [
    "src/backoff/exponential.js~exponentialbackoff#reset",
    "class/src/backoff/exponential.js~ExponentialBackoff.html#instance-method-reset",
    "src/backoff/exponential.js~ExponentialBackoff#reset",
    "method"
  ],
  [
    "src/builder.js",
    "file/src/builder.js.html",
    "src/builder.js",
    "file"
  ],
  [
    "src/builder.js~expression#and",
    "class/src/builder.js~Expression.html#instance-get-and",
    "src/builder.js~Expression#and",
    "member"
  ],
  [
    "src/builder.js~expression#div",
    "class/src/builder.js~Expression.html#instance-get-div",
    "src/builder.js~Expression#div",
    "member"
  ],
  [
    "src/builder.js~expression#doesntmatch",
    "class/src/builder.js~Expression.html#instance-get-doesntMatch",
    "src/builder.js~Expression#doesntMatch",
    "member"
  ],
  [
    "src/builder.js~expression#equals",
    "class/src/builder.js~Expression.html#instance-get-equals",
    "src/builder.js~Expression#equals",
    "member"
  ],
  [
    "src/builder.js~expression#exp",
    "class/src/builder.js~Expression.html#instance-method-exp",
    "src/builder.js~Expression#exp",
    "method"
  ],
  [
    "src/builder.js~expression#field",
    "class/src/builder.js~Expression.html#instance-method-field",
    "src/builder.js~Expression#field",
    "method"
  ],
  [
    "src/builder.js~expression#gt",
    "class/src/builder.js~Expression.html#instance-get-gt",
    "src/builder.js~Expression#gt",
    "member"
  ],
  [
    "src/builder.js~expression#gte",
    "class/src/builder.js~Expression.html#instance-get-gte",
    "src/builder.js~Expression#gte",
    "member"
  ],
  [
    "src/builder.js~expression#lt",
    "class/src/builder.js~Expression.html#instance-get-lt",
    "src/builder.js~Expression#lt",
    "member"
  ],
  [
    "src/builder.js~expression#lte",
    "class/src/builder.js~Expression.html#instance-get-lte",
    "src/builder.js~Expression#lte",
    "member"
  ],
  [
    "src/builder.js~expression#matches",
    "class/src/builder.js~Expression.html#instance-get-matches",
    "src/builder.js~Expression#matches",
    "member"
  ],
  [
    "src/builder.js~expression#minus",
    "class/src/builder.js~Expression.html#instance-get-minus",
    "src/builder.js~Expression#minus",
    "member"
  ],
  [
    "src/builder.js~expression#notequal",
    "class/src/builder.js~Expression.html#instance-get-notEqual",
    "src/builder.js~Expression#notEqual",
    "member"
  ],
  [
    "src/builder.js~expression#or",
    "class/src/builder.js~Expression.html#instance-get-or",
    "src/builder.js~Expression#or",
    "member"
  ],
  [
    "src/builder.js~expression#plus",
    "class/src/builder.js~Expression.html#instance-get-plus",
    "src/builder.js~Expression#plus",
    "member"
  ],
  [
    "src/builder.js~expression#tag",
    "class/src/builder.js~Expression.html#instance-method-tag",
    "src/builder.js~Expression#tag",
    "method"
  ],
  [
    "src/builder.js~expression#times",
    "class/src/builder.js~Expression.html#instance-get-times",
    "src/builder.js~Expression#times",
    "member"
  ],
  [
    "src/builder.js~expression#tostring",
    "class/src/builder.js~Expression.html#instance-method-toString",
    "src/builder.js~Expression#toString",
    "method"
  ],
  [
    "src/builder.js~expression#value",
    "class/src/builder.js~Expression.html#instance-method-value",
    "src/builder.js~Expression#value",
    "method"
  ],
  [
    "src/builder.js~measurement#db",
    "class/src/builder.js~Measurement.html#instance-method-db",
    "src/builder.js~Measurement#db",
    "method"
  ],
  [
    "src/builder.js~measurement#name",
    "class/src/builder.js~Measurement.html#instance-method-name",
    "src/builder.js~Measurement#name",
    "method"
  ],
  [
    "src/builder.js~measurement#policy",
    "class/src/builder.js~Measurement.html#instance-method-policy",
    "src/builder.js~Measurement#policy",
    "method"
  ],
  [
    "src/builder.js~measurement#tostring",
    "class/src/builder.js~Measurement.html#instance-method-toString",
    "src/builder.js~Measurement#toString",
    "method"
  ],
  [
    "src/grammar/ds.js",
    "file/src/grammar/ds.js.html",
    "src/grammar/ds.js",
    "file"
  ],
  [
    "src/grammar/ds.js~fieldtype",
    "typedef/index.html#static-typedef-FieldType",
    "src/grammar/ds.js~FieldType",
    "typedef"
  ],
  [
    "src/grammar/ds.js~raw#constructor",
    "class/src/grammar/ds.js~Raw.html#instance-constructor-constructor",
    "src/grammar/ds.js~Raw#constructor",
    "method"
  ],
  [
    "src/grammar/ds.js~raw#getvalue",
    "class/src/grammar/ds.js~Raw.html#instance-method-getValue",
    "src/grammar/ds.js~Raw#getValue",
    "method"
  ],
  [
    "src/grammar/escape.js",
    "file/src/grammar/escape.js.html",
    "src/grammar/escape.js",
    "file"
  ],
  [
    "src/grammar/index.js",
    "file/src/grammar/index.js.html",
    "src/grammar/index.js",
    "file"
  ],
  [
    "src/grammar/times.js",
    "file/src/grammar/times.js.html",
    "src/grammar/times.js",
    "file"
  ],
  [
    "src/host.js",
    "file/src/host.js.html",
    "src/host.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~influxdb#_createschema",
    "class/src/index.js~InfluxDB.html#instance-method-_createSchema",
    "src/index.js~InfluxDB#_createSchema",
    "method"
  ],
  [
    "src/index.js~influxdb#_defaultdb",
    "class/src/index.js~InfluxDB.html#instance-method-_defaultDB",
    "src/index.js~InfluxDB#_defaultDB",
    "method"
  ],
  [
    "src/index.js~influxdb#_getqueryopts",
    "class/src/index.js~InfluxDB.html#instance-method-_getQueryOpts",
    "src/index.js~InfluxDB#_getQueryOpts",
    "method"
  ],
  [
    "src/index.js~influxdb#_schema",
    "class/src/index.js~InfluxDB.html#instance-member-_schema",
    "src/index.js~InfluxDB#_schema",
    "member"
  ],
  [
    "src/index.js~influxdb#addschema",
    "class/src/index.js~InfluxDB.html#instance-method-addSchema",
    "src/index.js~InfluxDB#addSchema",
    "method"
  ],
  [
    "src/index.js~influxdb#alterretentionpolicy",
    "class/src/index.js~InfluxDB.html#instance-method-alterRetentionPolicy",
    "src/index.js~InfluxDB#alterRetentionPolicy",
    "method"
  ],
  [
    "src/index.js~influxdb#constructor",
    "class/src/index.js~InfluxDB.html#instance-constructor-constructor",
    "src/index.js~InfluxDB#constructor",
    "method"
  ],
  [
    "src/index.js~influxdb#createcontinuousquery",
    "class/src/index.js~InfluxDB.html#instance-method-createContinuousQuery",
    "src/index.js~InfluxDB#createContinuousQuery",
    "method"
  ],
  [
    "src/index.js~influxdb#createdatabase",
    "class/src/index.js~InfluxDB.html#instance-method-createDatabase",
    "src/index.js~InfluxDB#createDatabase",
    "method"
  ],
  [
    "src/index.js~influxdb#createretentionpolicy",
    "class/src/index.js~InfluxDB.html#instance-method-createRetentionPolicy",
    "src/index.js~InfluxDB#createRetentionPolicy",
    "method"
  ],
  [
    "src/index.js~influxdb#createuser",
    "class/src/index.js~InfluxDB.html#instance-method-createUser",
    "src/index.js~InfluxDB#createUser",
    "method"
  ],
  [
    "src/index.js~influxdb#dropcontinuousquery",
    "class/src/index.js~InfluxDB.html#instance-method-dropContinuousQuery",
    "src/index.js~InfluxDB#dropContinuousQuery",
    "method"
  ],
  [
    "src/index.js~influxdb#dropdatabase",
    "class/src/index.js~InfluxDB.html#instance-method-dropDatabase",
    "src/index.js~InfluxDB#dropDatabase",
    "method"
  ],
  [
    "src/index.js~influxdb#dropmeasurement",
    "class/src/index.js~InfluxDB.html#instance-method-dropMeasurement",
    "src/index.js~InfluxDB#dropMeasurement",
    "method"
  ],
  [
    "src/index.js~influxdb#dropretentionpolicy",
    "class/src/index.js~InfluxDB.html#instance-method-dropRetentionPolicy",
    "src/index.js~InfluxDB#dropRetentionPolicy",
    "method"
  ],
  [
    "src/index.js~influxdb#dropseries",
    "class/src/index.js~InfluxDB.html#instance-method-dropSeries",
    "src/index.js~InfluxDB#dropSeries",
    "method"
  ],
  [
    "src/index.js~influxdb#dropshard",
    "class/src/index.js~InfluxDB.html#instance-method-dropShard",
    "src/index.js~InfluxDB#dropShard",
    "method"
  ],
  [
    "src/index.js~influxdb#dropuser",
    "class/src/index.js~InfluxDB.html#instance-method-dropUser",
    "src/index.js~InfluxDB#dropUser",
    "method"
  ],
  [
    "src/index.js~influxdb#getdatabasenames",
    "class/src/index.js~InfluxDB.html#instance-method-getDatabaseNames",
    "src/index.js~InfluxDB#getDatabaseNames",
    "method"
  ],
  [
    "src/index.js~influxdb#getmeasurements",
    "class/src/index.js~InfluxDB.html#instance-method-getMeasurements",
    "src/index.js~InfluxDB#getMeasurements",
    "method"
  ],
  [
    "src/index.js~influxdb#getseries",
    "class/src/index.js~InfluxDB.html#instance-method-getSeries",
    "src/index.js~InfluxDB#getSeries",
    "method"
  ],
  [
    "src/index.js~influxdb#getusers",
    "class/src/index.js~InfluxDB.html#instance-method-getUsers",
    "src/index.js~InfluxDB#getUsers",
    "method"
  ],
  [
    "src/index.js~influxdb#grantadminprivilege",
    "class/src/index.js~InfluxDB.html#instance-method-grantAdminPrivilege",
    "src/index.js~InfluxDB#grantAdminPrivilege",
    "method"
  ],
  [
    "src/index.js~influxdb#grantprivilege",
    "class/src/index.js~InfluxDB.html#instance-method-grantPrivilege",
    "src/index.js~InfluxDB#grantPrivilege",
    "method"
  ],
  [
    "src/index.js~influxdb#ping",
    "class/src/index.js~InfluxDB.html#instance-method-ping",
    "src/index.js~InfluxDB#ping",
    "method"
  ],
  [
    "src/index.js~influxdb#query",
    "class/src/index.js~InfluxDB.html#instance-method-query",
    "src/index.js~InfluxDB#query",
    "method"
  ],
  [
    "src/index.js~influxdb#queryraw",
    "class/src/index.js~InfluxDB.html#instance-method-queryRaw",
    "src/index.js~InfluxDB#queryRaw",
    "method"
  ],
  [
    "src/index.js~influxdb#revokeadminprivilege",
    "class/src/index.js~InfluxDB.html#instance-method-revokeAdminPrivilege",
    "src/index.js~InfluxDB#revokeAdminPrivilege",
    "method"
  ],
  [
    "src/index.js~influxdb#revokeprivilege",
    "class/src/index.js~InfluxDB.html#instance-method-revokePrivilege",
    "src/index.js~InfluxDB#revokePrivilege",
    "method"
  ],
  [
    "src/index.js~influxdb#setpassword",
    "class/src/index.js~InfluxDB.html#instance-method-setPassword",
    "src/index.js~InfluxDB#setPassword",
    "method"
  ],
  [
    "src/index.js~influxdb#showcontinousqueries",
    "class/src/index.js~InfluxDB.html#instance-method-showContinousQueries",
    "src/index.js~InfluxDB#showContinousQueries",
    "method"
  ],
  [
    "src/index.js~influxdb#showretentionpolicies",
    "class/src/index.js~InfluxDB.html#instance-method-showRetentionPolicies",
    "src/index.js~InfluxDB#showRetentionPolicies",
    "method"
  ],
  [
    "src/index.js~influxdb#showshards",
    "class/src/index.js~InfluxDB.html#instance-method-showShards",
    "src/index.js~InfluxDB#showShards",
    "method"
  ],
  [
    "src/index.js~influxdb#writemeasurement",
    "class/src/index.js~InfluxDB.html#instance-method-writeMeasurement",
    "src/index.js~InfluxDB#writeMeasurement",
    "method"
  ],
  [
    "src/index.js~influxdb#writepoints",
    "class/src/index.js~InfluxDB.html#instance-method-writePoints",
    "src/index.js~InfluxDB#writePoints",
    "method"
  ],
  [
    "src/pool.js",
    "file/src/pool.js.html",
    "src/pool.js",
    "file"
  ],
  [
    "src/pool.js~pool#_disablehost",
    "class/src/pool.js~Pool.html#instance-method-_disableHost",
    "src/pool.js~Pool#_disableHost",
    "method"
  ],
  [
    "src/pool.js~pool#_enablehost",
    "class/src/pool.js~Pool.html#instance-method-_enableHost",
    "src/pool.js~Pool#_enableHost",
    "method"
  ],
  [
    "src/pool.js~pool#_gethost",
    "class/src/pool.js~Pool.html#instance-method-_getHost",
    "src/pool.js~Pool#_getHost",
    "method"
  ],
  [
    "src/pool.js~pool#addhost",
    "class/src/pool.js~Pool.html#instance-method-addHost",
    "src/pool.js~Pool#addHost",
    "method"
  ],
  [
    "src/pool.js~pool#constructor",
    "class/src/pool.js~Pool.html#instance-constructor-constructor",
    "src/pool.js~Pool#constructor",
    "method"
  ],
  [
    "src/pool.js~pool#discard",
    "class/src/pool.js~Pool.html#instance-method-discard",
    "src/pool.js~Pool#discard",
    "method"
  ],
  [
    "src/pool.js~pool#gethostsavailable",
    "class/src/pool.js~Pool.html#instance-method-getHostsAvailable",
    "src/pool.js~Pool#getHostsAvailable",
    "method"
  ],
  [
    "src/pool.js~pool#gethostsdisabled",
    "class/src/pool.js~Pool.html#instance-method-getHostsDisabled",
    "src/pool.js~Pool#getHostsDisabled",
    "method"
  ],
  [
    "src/pool.js~pool#hostisavailable",
    "class/src/pool.js~Pool.html#instance-method-hostIsAvailable",
    "src/pool.js~Pool#hostIsAvailable",
    "method"
  ],
  [
    "src/pool.js~pool#json",
    "class/src/pool.js~Pool.html#instance-method-json",
    "src/pool.js~Pool#json",
    "method"
  ],
  [
    "src/pool.js~pool#ping",
    "class/src/pool.js~Pool.html#instance-method-ping",
    "src/pool.js~Pool#ping",
    "method"
  ],
  [
    "src/pool.js~pool#stream",
    "class/src/pool.js~Pool.html#instance-method-stream",
    "src/pool.js~Pool#stream",
    "method"
  ],
  [
    "src/pool.js~pool#text",
    "class/src/pool.js~Pool.html#instance-method-text",
    "src/pool.js~Pool#text",
    "method"
  ],
  [
    "src/results.js",
    "file/src/results.js.html",
    "src/results.js",
    "file"
  ],
  [
    "src/schema.js",
    "file/src/schema.js.html",
    "src/schema.js",
    "file"
  ],
  [
    "src/schema.js~schema#_ref",
    "class/src/schema.js~Schema.html#instance-method-_ref",
    "src/schema.js~Schema#_ref",
    "method"
  ],
  [
    "src/schema.js~schema#checktags",
    "class/src/schema.js~Schema.html#instance-method-checkTags",
    "src/schema.js~Schema#checkTags",
    "method"
  ],
  [
    "src/schema.js~schema#coercefields",
    "class/src/schema.js~Schema.html#instance-method-coerceFields",
    "src/schema.js~Schema#coerceFields",
    "method"
  ],
  [
    "unit/backoff.test.js",
    "test-file/unit/backoff.test.js.html",
    "unit/backoff.test.js",
    "testFile"
  ],
  [
    "unit/builder.test.js",
    "test-file/unit/builder.test.js.html",
    "unit/builder.test.js",
    "testFile"
  ],
  [
    "unit/grammar.test.js",
    "test-file/unit/grammar.test.js.html",
    "unit/grammar.test.js",
    "testFile"
  ],
  [
    "unit/influx.test.js",
    "test-file/unit/influx.test.js.html",
    "unit/influx.test.js",
    "testFile"
  ],
  [
    "unit/pool.test.js",
    "test-file/unit/pool.test.js.html",
    "unit/pool.test.js",
    "testFile"
  ],
  [
    "unit/result.test.js",
    "test-file/unit/result.test.js.html",
    "unit/result.test.js",
    "testFile"
  ],
  [
    "unit/schema.test.js",
    "test-file/unit/schema.test.js.html",
    "unit/schema.test.js",
    "testFile"
  ]
]